### ISSUE TITLE
Add tag navigation to definition of citation, etc. with coc-definition

### ISSUE THREAD

**Issue by mawkler** [neoclide/coc-vimtex#10]
Vimtex gives the ability to [navigate using tags](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L311) to definition of `\cite{...}`, `\label{...}`, etc. with `<c-]>`, but this requires ctags. Would it be possible to add this feature to `<Plug>(coc-definition)`?

**Comment by chemzqm** [comment]
Use tex language server https://github.com/neoclide/coc.nvim/wiki/Language-servers#latex or just use `<c-]>` if you're using vimtex.

**Comment by mawkler** [comment]
Thanks! I Installed [coc-texlab](https://github.com/fannheyward/coc-texlab) which has the functionality I requested.
