### ISSUE TITLE
Go to Declaration on project files not working

### ISSUE THREAD

**Issue by andregpss** [neoclide/coc-vimtex#11]
When i type `gd` or `gD` mapping key to find the definition of a reference located on an other project file, the following error message comes:

> [coc.nvim] Definition provider not found for current document

All the other features are working (compiling, completion, pdf viewing, TocToogle...). Goto file `gf `is also working.

I am working on an multi-file project using subfile package.

There is no error on Coc log, either on Vimtex log.

I am using NeoVim 0.4.3, coc 0.0.74 on Windows 10.

TEX Example (`sec:background` declared on other file)

> \documentclass[main]{subfiles}
> \begin{document}
> \section{Related Work}\label{sec:related}
> As we mentioned before in Section \ref{sec:background}, ....
> \end{document}

**Comment by karimknaebel** [comment]
https://github.com/neoclide/coc-vimtex/issues/10#event-3058935261

**Comment by chemzqm** [comment]
No such support use language server for tex instead.

**Comment by andregpss** [comment]
I am using [ctags](http://ctags.sourceforge.net/) now for solving this issue. I am also using [gutentags](https://github.com/ludovicchabant/vim-gutentags) to generate the tags.
Finally, i mapped the following command:

> nmap \<leader\>d :exec "tag ".expand("\<cword\>")\<CR\>

I also added to `vimrc` file:

> let g:gutentags_project_root = ['main.tex']

**Comment by chemzqm** [comment]
There is https://github.com/fannheyward/coc-texlab could help.
