### ISSUE TITLE
autoTrigger "none" ignored when coc-vimtex is installed

### ISSUE THREAD

**Issue by Fubukimaru** [neoclide/coc-vimtex#12]
Hello,

I have in my coc-settings.json the following configuration:
```
{
    "suggest.autoTrigger": "none"
}
```
It works perfectly except for LaTeX. In this case, if I have coc-vimtex installed, the completion is automatically triggered everything, leading to a slowdown when there are a lot of different words in the file.

If i do `:CocUninstall coc-vimtex` it works again as expected.

What do you need to reproduce this issue?

Thank you for your support.

**Comment by chemzqm** [comment]
Should be caused by other vim plugin, try minimal vimrc.

**Comment by Fubukimaru** [comment]
I have tested it in another computer and it works correctly with the same .vimrc, so it's probably some version specific issues.

Thanks for your support and sorry for the inconvenience :)
