### ISSUE TITLE
some times vimtex don't work

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [neoclide/coc-vimtex#13]

**Comment by Unknown-Chinese-User** [comment]
I usually write a file that only contain main body without Macro packages, but every time I nvim it, the coc-vimtex doesn't work. 
The error message is `[coc.nvim]vimtex not loaded`(I'm sorry, it seems that I can't upload image now)
but when I edit the main.tex, the coc-vimtex works normally.

**Comment by Unknown-Chinese-User** [comment]
By the way, it seems that the snippets also don't work

**Comment by chemzqm** [comment]
The plugin not loaded by vim

**Comment by Unknown-Chinese-User** [comment]
> The plugin not loaded by vim

what do you mean?
I use nvim.
I think this is because I didn't use it properly, but I cannot find where is my fault.

**Comment by Unknown-Chinese-User** [comment]
@chemzqm I made a conversation in zhihu. Please reply me at zhihu

**Comment by chemzqm** [comment]
You have to make sure vimtex is in your $rtp, use `:echo &rtp`

**Comment by Unknown-Chinese-User** [comment]
I'm sure I have vimtex, because the autocompete is okay when I open a nomal tex file(which contains \documentclass \begin{document} and \end{document})

**Comment by Unknown-Chinese-User** [comment]
when  I shut down the vimtex plug, the same error is reported in the main file ,I think this is because vimtex fails to load in the new file. Maybe I need to rise a new issue in vimtex

**Comment by chemzqm** [comment]
Use `:echo g:vimtex#re#deoplete`

**Comment by chemzqm** [comment]
Should be problem of your lazyload by vim-plug or other plugin.
