### ISSUE TITLE
Snippet doesn't work

### ISSUE THREAD

**Issue by FelipeMarcelino** [neoclide/coc-vimtex#14]
The autocomplete is working using coc-vimtex. However, the snippets don't work. It is the expected behavior?

**Comment by chemzqm** [comment]
Please explain snippets don't work

**Comment by FelipeMarcelino** [comment]
When I type \begin for example, the expected behavior is to expand the snippet to this: 

snippet begin \begin{} ... \end{} block
	\\begin{${1:env}}
		${0:${VISUAL}}
	\\end{$1}

https://github.com/honza/vim-snippets/blob/master/snippets/tex.snippets

But, it doesn't work as expected. Expand snippet option apparently doesn't appear. 
@chemzqm

**Comment by chemzqm** [comment]
coc-vimtex does completion from vimtex only, no support for snippet.

**Comment by FelipeMarcelino** [comment]
Ok, my apologies. I will take a look into vim-snippets!
