### ISSUE TITLE
How shall I configure it to make it like VSCode

### ISSUE THREAD

**Issue by dlejay** [neoclide/coc-vimtex#15]
I would like to have the following features:

* Start showing me suggestions only after I have typed `\` and 2 other characters;
* Have `coc` look at `\newcommand`s in `\include` `\input` files to make their completion available in the current file;
* Have case insensitive and fuzzy completion. Example: I define
`\newcommand{\OnceUponATime}{Test}`. Then I would like to see this new command suggested after I input something like `\upon` or `\ouat` etc.

I have spent a couple hours trying different `coc` settings but I couldn't achieve this.

My coc-settings.json so far:
```
{
	"suggest.minTriggerInputLength": 2,
	"coc.source.around.firstMatch": false,
	"coc.source.buffer.firstMatch": false,
}
```

**Comment by chemzqm** [comment]
It's simple completion provider for coc.nvim using vimtex, the trigger is regex from vimtex.

**Comment by chemzqm** [comment]
> I have spent a couple hours trying

It would be much better if you can learn basic viml or typescript so you can just read the code, which could be much faster.
