### ISSUE TITLE
Return key does nothing when completion menu opened without anything selected

### ISSUE THREAD

**Issue by willfindlay** [neoclide/coc-vimtex#16]
# Issue
If the completion menu opens and I press enter with nothing selected, the completion menu flickers off, then immediately re-opens. This no longer occurs when I disable the extension.

Edit: same problem when pressing `<C-y>` directly.

# Expected Behavior
I expect pressing enter to close the completion menu.

# Reproduction Steps
Running coc.nvim, vimtex, and with the coc-vimtex extension installed, open up some .tex file and type something like "lst" to bring up the completion menu. Then press enter and watch the menu close briefly and re-open.

Here is the relevant part of my init.vim:
```vim
" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<C-t>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-d>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
inoremap <silent><expr> <c-space> coc#refresh()

" Use <cr> to confirm completion, `<C-g>u` means break undo chain at current position.
" Coc only does snippet and additional edit on confirm.
noremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

I do not have any coc-vimtex related configuration options in my coc-settings.json.

**Comment by chemzqm** [comment]
Need fix for trigger on cursor moved.

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.
