### ISSUE TITLE
I've installed vimtex through vim-plug and then coc-vimtex for coc.nvim, but still I got "[coc.nvim] vimtex not loaded" when attempt to open a *.tex file

### ISSUE THREAD

**Issue by ricciolino** [neoclide/coc-vimtex#18]
I've installed vimtex and then coc-vimtex (latexmk is installed), but still I got "[coc.nvim] vimtex not loaded" when I open a tex file.
Which could be the problem?

_Originally posted by @ricciolino in https://github.com/neoclide/coc-vimtex/issues/6#issuecomment-667664260_

**Comment by lervag** [comment]
Hi @ricciolino. When you write:

> I've installed vimtex and then coc-vimtex (latexmk is installed)

Can you be more specific? In particular, _how_ have you install vimtex?

**Comment by ricciolino** [comment]
I've installed it using vim-plug:

Plug 'lervag/vimtex'

**Comment by lervag** [comment]
Ok. After you've opened the tex file, does vimtex "seem" loaded? I.e., does e.g. `:VimtexInfo` work?

**Comment by ricciolino** [comment]
No it says "E492: Not an editor command: VimtexInfo"

**Comment by lervag** [comment]
So, vimtex is _not_ installed. Did you do `:PlugInstall`?

**Comment by ricciolino** [comment]
Yes, I did as usually,!
This is from my .vimrc :
```
call plug#begin()
" This is where we will add plugins to install
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdcommenter'
Plug 'ToruIwashita/git-switcher.vim'
Plug 'lervag/vimtex'
call plug#end()
```
I did:
`:PlugInstall`
and everything seems fine, then I use:
`:CocInstall coc-vimtex`
and at this point appear the error saying:
`[coc.nvim] vimtex not loaded`

**Comment by lervag** [comment]
Ok. So, before you dod `CocInstall`, did you verify that e.g. `:VimtexInfo` works?

What is the latex file you are working on?

Do you have `let g:tex_flavor = 'latex'` in your vimrc?

**Comment by ricciolino** [comment]
> Do you have let g:tex_flavor = 'latex' in your vimrc?

I didn't have this !!!
Oh my god thank you so much I was going crazy!
Thank you!
Now everything works!

**Comment by lervag** [comment]
> I didn't have this !!!
> Oh my god thank you so much I was going crazy!
> Thank you!
> Now everything works!

Great, happy to hear it. Note that this is documented at the very beginning of the vimtex docs! This seems to indicate that you never tried to read the documentation. ;)

**Comment by ricciolino** [comment]
Yes, I admit, we never opened it, now I have seen that it is documented right at the beginning!
I am mortified, I am still a novice ... I have to gain experience!
thanks again for the help.

**Comment by lervag** [comment]
No problem, happy to help. Good luck on your journey :)
