### ISSUE TITLE
"yarn build" does not work

### ISSUE THREAD

**Issue by pappasam** [neoclide/coc-vimtex#19]
This coc extension cannot be installed similarly to other coc extensions. It's missing the `package.json` script for build. Therefore, my standard `yarn install --frozen-lockfile && yarn build` post-installation hook gives the following error:

```console
$ yarn install --frozen-lockfile && yarn build
yarn install v1.22.4
[1/5] Validating package.json...
warning coc-vimtex@1.0.4: The engine "coc" appears to be invalid.
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.12s.
yarn run v1.22.4
error Command "build" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chemzqm** [comment]
It's javascript, no need to build and use `yarn install --frozen-lockfile` is enough for all coc.nvim extensions.
