### ISSUE TITLE
What does this extension actually do?

### ISSUE THREAD

**Issue by newptcai** [neoclide/coc-vimtex#22]
I have installed both `vimtex` and `coc` with extension `coc-texlab`. Everything seems to work well. So what function does this extension actually offer? Any example?

**Comment by chemzqm** [comment]
Tex completion source use vimtex.

**Comment by newptcai** [comment]
Yes. But do you any concrete example what completions this extension can do that coc-texlab cannot do?

**Comment by chemzqm** [comment]
Ask creator of vimtex and texlab.
