### ISSUE TITLE
Red warning pop up at bottom of vim when i open the tex file

### ISSUE THREAD

**Issue by daVimci** [neoclide/coc-vimtex#33]
[coc.nvim]: UnhandledRejection: TypeError: str.indexof is not a function

After I reinstall the coc-vimtex, it still appears at the bottom of vim. 
![Screenshot from 2022-03-22 14-42-20](https://user-images.githubusercontent.com/87670378/159423077-9927e25b-db6b-444a-9bfa-7e59afad73a5.png)

**Comment by ryanr549** [comment]
I have exactly the same problem. Maybe it's due to some library conflicts and hopefully the developers will fix it as soon as possible.
