### ISSUE TITLE
other completion source is blocked by coc-vimtex

### ISSUE THREAD

**Issue by voldikss** [neoclide/coc-vimtex#5]
最近使用 coc-vimtex 遇到这个问题，查了一下好像是由这个提交导致的
https://github.com/neoclide/coc.nvim/commit/8668f301e439dd6349a18d83b6b6cd95687317aa

问题就是，只有在输入 `\` 时才会触发补全，否则不会弹出补全列表

**Comment by chemzqm** [comment]
Fixed

**Comment by WangCQU** [comment]
能否加入一个选项，只在输入 \  时才会触发补全。对于latex正文都进行补全的化，很影响输入

**Comment by chemzqm** [comment]
vimtex 问题，建议可以试试 tex 的 language server
