### ISSUE TITLE
[coc.nvim] vimtex not loaded

### ISSUE THREAD

**Issue by ahmedselim2017** [neoclide/coc-vimtex#6]
When I open a tex file it doesn't load.

**Comment by chemzqm** [comment]
It need vimtex to work

**Comment by Marco-Israel** [comment]
Same problem here. Vimtex is installed and running. coc-vimtex also.

**Comment by ricciolino** [comment]
I've installed vimtex and then coc-vimtex, but still I got "[coc.nvim] vimtex not loaded".
Which could be the problem?

**Comment by lervag** [comment]
Please see #18 for followup discussion on this. And note: When you say vimtex is installed, but that coc-vimtex says "vimtex is not loaded", then it is clear that you have not installed things correctly. To further help, you should specify in more detail what you did to install.
