### ISSUE TITLE
Returns true for `echo CocHasProvider("format")`

### ISSUE THREAD

**Issue by GordianDziwis** [neoclide/coc-vimtex#9]
I have this line in my vimrc to make ale and coc play nicely together:

```vim
nmap <expr><localleader>f  CocHasProvider("format") ? '<Plug>(coc-format)' : ':ALEFix<cr>'
```

**Comment by karimknaebel** [comment]
What is the problem?

**Comment by karimknaebel** [comment]
By the way, you might want to try out https://github.com/fannheyward/coc-texlab

**Comment by GordianDziwis** [comment]
Should not it return false, because coc-vimtex does not provide formating? `call CocActionAsync('format')` seems to have no effect.

**Comment by GordianDziwis** [comment]
Thanks, I will try it out.
